In [65]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.metrics import confusion_matrix, classification_report, precision_score

In [66]:
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split

In [67]:
from sklearn.cross_decomposition import PLSRegression as PLSR

In [68]:
# Import 'coffee_region' sheet file from 'coffee.xlsx' Excel file
df = pd.read_excel('/Users/giorgiofelizzato/Desktop/RISEN project/Articles/IMS_GC-QEPAS data fusion/ims/IMS.xlsx', sheet_name='Foglio1', index_col=0, header=0)
df.head()

Class   0.52   0.54   0.56   0.58    0.6   0.62   0.64   0.66  \
Sample_id                                                                 
TATP_1     TATP  0.076  0.081  0.080  0.077  0.081  0.082  0.080  0.079   
TATP_2     TATP  0.073  0.079  0.081  0.081  0.080  0.081  0.079  0.077   
TATP_3     TATP  0.075  0.079  0.078  0.080  0.082  0.079  0.079  0.080   
TATP_4     TATP  0.079  0.077  0.080  0.080  0.079  0.079  0.080  0.079   
TATP_5     TATP  0.083  0.080  0.080  0.080  0.078  0.079  0.082  0.085   

            0.68  ...  13.68   13.7  13.72  13.74  13.76  13.78   13.8  13.82  \
Sample_id         ...                                                           
TATP_1     0.082  ...  0.080  0.078  0.080  0.081  0.081  0.081  0.081  0.079   
TATP_2     0.083  ...  0.082  0.081  0.081  0.079  0.080  0.084  0.071  0.083   
TATP_3     0.079  ...  0.084  0.082  0.078  0.078  0.080  0.081  0.081  0.082   
TATP_4     0.077  ...  0.080  0.084  0.072  0.080  0.079  0.079  0.079  0.080   
TATP_5     0.077  ...  0.066  0.078  0.077  0.079  0.078  0.077  0.079  0.079   

           13.84  13.86  
Sample_id                
TATP_1     0.082  0.035  
TATP_2     0.078  0.040  
TATP_3     0.082  0.040  
TATP_4     0.080  0.040  
TATP_5     0.079  0.035  

[5 rows x 669 columns]

In [69]:
X = df.iloc[:,1:]
X

0.52   0.54   0.56   0.58   0.60   0.62   0.64   0.66   0.68   \
Sample_id                                                                   
TATP_1      0.076  0.081  0.080  0.077  0.081  0.082  0.080  0.079  0.082   
TATP_2      0.073  0.079  0.081  0.081  0.080  0.081  0.079  0.077  0.083   
TATP_3      0.075  0.079  0.078  0.080  0.082  0.079  0.079  0.080  0.079   
TATP_4      0.079  0.077  0.080  0.080  0.079  0.079  0.080  0.079  0.077   
TATP_5      0.083  0.080  0.080  0.080  0.078  0.079  0.082  0.085  0.077   
TATP_6      0.081  0.080  0.081  0.080  0.081  0.084  0.082  0.081  0.081   
TATP_7      0.087  0.068  0.081  0.081  0.084  0.073  0.080  0.080  0.080   
TATP_8      0.077  0.083  0.081  0.078  0.078  0.082  0.079  0.079  0.081   
TATP_9      0.083  0.080  0.080  0.081  0.080  0.078  0.077  0.081  0.083   
TATP_10     0.081  0.080  0.082  0.081  0.080  0.074  0.082  0.084  0.072   
TATP_11     0.083  0.073  0.080  0.080  0.079  0.082  0.079  0.078  0.078   
TATP_12     0.080  0.080  0.081  0.081  0.080  0.079  0.079  0.079  0.080   
TATP_13     0.079  0.081  0.085  0.074  0.080  0.079  0.080  0.079  0.077   
TATP_14     0.080  0.078  0.079  0.078  0.079  0.079  0.080  0.077  0.077   
Acetone_1   0.020  0.018  0.014  0.019  0.014  0.015  0.021  0.017  0.017   
Acetone_2   0.017  0.015  0.014  0.015  0.013  0.019  0.024  0.020  0.020   
Acetone_3   0.018  0.022  0.020  0.022  0.020  0.016  0.020  0.020  0.018   
Acetone_4   0.023  0.019  0.015  0.019  0.016  0.025  0.026  0.021  0.020   
Acetone_5   0.018  0.015  0.022  0.022  0.019  0.020  0.025  0.023  0.022   
Acetone_6   0.020  0.021  0.019  0.018  0.022  0.017  0.021  0.022  0.020   
Acetone_7   0.017  0.017  0.020  0.021  0.020  0.017  0.021  0.020  0.022   
Acetone_8   0.018  0.020  0.022  0.022  0.022  0.018  0.017  0.019  0.019   
Acetone_9   0.018  0.016  0.023  0.018  0.023  0.025  0.026  0.022  0.020   
Acetone_10  0.016  0.016  0.019  0.024  0.019  0.016  0.022  0.024  0.022   
Acetone_11  0.019  0.024  0.023  0.018  0.018  0.021  0.019  0.021  0.018   
Acetone_12  0.017  0.013  0.016  0.017  0.017  0.019  0.019  0.017  0.018   
Acetone_13  0.019  0.019  0.019  0.015  0.016  0.017  0.016  0.014  0.017   
Acetone_14  0.028  0.024  0.021  0.017  0.017  0.026  0.018  0.018  0.018   
Acetone_15  0.014  0.017  0.018  0.020  0.020  0.020  0.023  0.024  0.026   
DMMP_1      0.022  0.022  0.019  0.016  0.021  0.019  0.020  0.018  0.019   
DMMP_2      0.020  0.019  0.018  0.017  0.018  0.020  0.022  0.023  0.021   
DMMP_3      0.016  0.022  0.021  0.020  0.020  0.020  0.020  0.018  0.018   
DMMP_4      0.015  0.020  0.020  0.024  0.021  0.022  0.021  0.023  0.023   
DMMP_5      0.016  0.015  0.020  0.020  0.018  0.018  0.018  0.024  0.024   
DMMP_6      0.018  0.024  0.016  0.020  0.019  0.018  0.019  0.022  0.020   
DMMP_7      0.017  0.020  0.019  0.020  0.020  0.021  0.017  0.020  0.020   
DMMP_8      0.025  0.022  0.023  0.024  0.022  0.025  0.023  0.022  0.021   
DMMP_9      0.021  0.022  0.022  0.021  0.021  0.018  0.018  0.019  0.021   
DMMP_10     0.022  0.016  0.021  0.017  0.019  0.023  0.021  0.021  0.026   
DMMP_11     0.018  0.016  0.014  0.017  0.017  0.017  0.020  0.018  0.021   
DMMP_12     0.014  0.019  0.021  0.019  0.021  0.021  0.025  0.022  0.022   
DMMP_13     0.027  0.024  0.022  0.020  0.018  0.021  0.021  0.022  0.023   
DMMP_14     0.020  0.020  0.020  0.025  0.017  0.016  0.018  0.023  0.019   

            0.70   ...  13.68  13.70  13.72  13.74  13.76  13.78  13.80  \
Sample_id          ...                                                    
TATP_1      0.079  ...  0.080  0.078  0.080  0.081  0.081  0.081  0.081   
TATP_2      0.081  ...  0.082  0.081  0.081  0.079  0.080  0.084  0.071   
TATP_3      0.079  ...  0.084  0.082  0.078  0.078  0.080  0.081  0.081   
TATP_4      0.076  ...  0.080  0.084  0.072  0.080  0.079  0.079  0.079   
TATP_5      0.082  ...  0.066  0.078  0.077  0.079  0.078  0.077  0.079   
TATP_6      0.078  ..

In [70]:
# Checking the presence missing values
df.isnull().sum()

Class    0
0.52     0
0.54     0
0.56     0
0.58     0
        ..
13.78    0
13.8     0
13.82    0
13.84    0
13.86    0
Length: 669, dtype: int64

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43 entries, TATP_1 to DMMP_14
Columns: 669 entries, Class to 13.86
dtypes: float64(668), object(1)
memory usage: 225.1+ KB


In [72]:
df.describe()

0.52       0.54       0.56       0.58       0.60       0.62   \
count  43.000000  43.000000  43.000000  43.000000  43.000000  43.000000   
mean    0.038837   0.038512   0.039302   0.039047   0.038814   0.039070   
std     0.029001   0.028311   0.029164   0.028499   0.029085   0.028428   
min     0.014000   0.013000   0.014000   0.015000   0.013000   0.015000   
25%     0.018000   0.018500   0.019000   0.018500   0.018000   0.018000   
50%     0.020000   0.022000   0.021000   0.021000   0.021000   0.021000   
75%     0.076500   0.077500   0.080000   0.078000   0.079000   0.078500   
max     0.087000   0.083000   0.085000   0.081000   0.084000   0.084000   

           0.64       0.66       0.68       0.70   ...      13.68      13.70  \
count  43.000000  43.000000  43.000000  43.000000  ...  43.000000  43.000000   
mean    0.039977   0.039884   0.039581   0.039326  ...   0.040279   0.040256   
std     0.028136   0.028205   0.027881   0.029049  ...   0.027874   0.028239   
min     0.016000   0.014000   0.017000   0.015000  ...   0.013000   0.016000   
25%     0.020000   0.020000   0.020000   0.018000  ...   0.021000   0.020000   
50%     0.022000   0.022000   0.022000   0.021000  ...   0.024000   0.023000   
75%     0.079000   0.078500   0.077000   0.079000  ...   0.078500   0.078500   
max     0.082000   0.085000   0.083000   0.085000  ...   0.084000   0.084000   

           13.72      13.74      13.76      13.78      13.80      13.82  \
count  43.000000  43.000000  43.000000  43.000000  43.000000  43.000000   
mean    0.040465   0.040465   0.040302   0.041140   0.040791   0.041070   
std     0.027901   0.027652   0.028118   0.028033   0.027571   0.027949   
min     0.016000   0.013000   0.014000   0.015000   0.015000   0.017000   
25%     0.021000   0.021500   0.021000   0.021000   0.021000   0.021500   
50%     0.024000   0.024000   0.023000   0.024000   0.024000   0.024000   
75%     0.078500   0.078500   0.079000   0.079000   0.079000   0.079000   
max     0.083000   0.085000   0.084000   0.084000   0.084000   0.083000   

           13.84      13.86  
count  43.000000  43.000000  
mean    0.041093   0.011860  
std     0.028041   0.034761  
min     0.018000  -0.035000  
25%     0.021000  -0.035000  
50%     0.023000   0.035000  
75%     0.079000   0.037500  
max     0.084000   0.040000  

[8 rows x 668 columns]

In [73]:
Y = df.loc[:,'Class']
Y

Sample_id
TATP_1           TATP
TATP_2           TATP
TATP_3           TATP
TATP_4           TATP
TATP_5           TATP
TATP_6           TATP
TATP_7           TATP
TATP_8           TATP
TATP_9           TATP
TATP_10          TATP
TATP_11          TATP
TATP_12          TATP
TATP_13          TATP
TATP_14          TATP
Acetone_1     acetone
Acetone_2     acetone
Acetone_3     acetone
Acetone_4     acetone
Acetone_5     acetone
Acetone_6     acetone
Acetone_7     acetone
Acetone_8     acetone
Acetone_9     acetone
Acetone_10    acetone
Acetone_11    acetone
Acetone_12    acetone
Acetone_13    acetone
Acetone_14    acetone
Acetone_15    acetone
DMMP_1           DMMP
DMMP_2           DMMP
DMMP_3           DMMP
DMMP_4           DMMP
DMMP_5           DMMP
DMMP_6           DMMP
DMMP_7           DMMP
DMMP_8           DMMP
DMMP_9           DMMP
DMMP_10          DMMP
DMMP_11          DMMP
DMMP_12          DMMP
DMMP_13          DMMP
DMMP_14          DMMP
Name: Class, dtype: object

In [74]:
# autoscale the data
from sklearn.preprocessing import scale
X_autosc = scale(X.values)
X_autosc

array([[ 1.29660731,  1.51855163,  1.41198289, ...,  1.373171  ,
         1.476067  ,  0.67354382],
       [ 1.19193751,  1.44707082,  1.44667733, ...,  1.51798118,
         1.33173299,  0.81908344],
       [ 1.26171738,  1.44707082,  1.34259402, ...,  1.48177863,
         1.476067  ,  0.81908344],
       ...,
       [-0.86656859, -0.69735348, -0.63498888, ..., -0.69037414,
        -0.72502665,  0.67354382],
       [-0.41299945, -0.51865146, -0.60029444, ..., -0.65417159,
        -0.61677615,  0.67354382],
       [-0.65722899, -0.66161308, -0.66968331, ..., -0.61796904,
        -0.54460914,  0.67354382]])

In [75]:
# Write the SNV function (is, actually, like autoscaling by row)
def snv(input_data):
  
    # Define a new array and populate it with the corrected data  
    output_data = np.zeros_like(input_data)
    for i in range(input_data.shape[0]):
 
        # Apply correction
        output_data[i,:] = (input_data[i,:] - np.mean(input_data[i,:])) / np.std(input_data[i,:])
 
    return output_data

In [76]:
# Compute the SNV on np data
Xsnv = snv(X.values)
Xsnv

array([[-0.59939413, -0.58920342, -0.59124156, ..., -0.5932797 ,
        -0.58716527, -0.68295801],
       [-0.50637416, -0.4964454 , -0.49313581, ..., -0.48982623,
        -0.49810019, -0.56098234],
       [-0.5957196 , -0.58742874, -0.58950145, ..., -0.58121059,
        -0.58121059, -0.66826465],
       ...,
       [-0.28256351, -0.27854558, -0.27693841, ..., -0.27613483,
        -0.27693841, -0.26568823],
       [-0.30701047, -0.31038571, -0.31263587, ..., -0.31151079,
        -0.31038571, -0.29800983],
       [-0.31412998, -0.31412998, -0.31412998, ..., -0.30964052,
        -0.30739578, -0.29729448]])

In [77]:
lda = LDA(n_components=2) # N-1 where N are the classes
scores_lda = lda.fit(X_autosc, Y).transform(X_autosc)

In [78]:
scores_lda

array([[ 46.11230424,   0.67036776],
       [ 47.34386286,  -0.11514391],
       [ 46.36350348,  -1.21873411],
       [ 43.96789617,  -1.38838569],
       [ 46.78643495,   0.21884249],
       [ 49.26743063,   0.25194314],
       [ 47.55505502,   1.26429697],
       [ 47.30308204,  -0.95887378],
       [ 47.62847412,  -0.64943089],
       [ 48.51652882,   0.54062129],
       [ 47.55471915,   0.2529615 ],
       [ 48.32872541,  -0.07008532],
       [ 46.8539048 ,   0.77469328],
       [ 47.98711441,   0.48619994],
       [-24.08271334,   2.36948294],
       [-23.0408271 ,   0.6912287 ],
       [-23.1669734 ,  -0.06221232],
       [-22.39337111,   1.37235938],
       [-22.21806574,   1.13907672],
       [-22.19341369,   0.45300317],
       [-22.9797753 ,   1.63551639],
       [-22.67734511,   2.56409836],
       [-21.3350137 ,   1.89568941],
       [-22.67529437,   2.8273131 ],
       [-22.93404339,   2.15948061],
       [-23.82033893,   3.12345049],
       [-24.33581853,   3.10495357],
 

In [79]:
print(lda.priors_)

[0.3255814  0.3255814  0.34883721]


In [80]:
print(lda.means_)

[[-0.67965823 -0.65906019 -0.67959601 ... -0.70071772 -0.69152054
  -0.49077313]
 [ 1.42869063  1.42920061  1.43428646 ...  1.4352325   1.43482871
   0.78789638]
 [-0.69909691 -0.71879773 -0.70437775 ... -0.68554713 -0.69375429
  -0.27731503]]


In [81]:
print(lda.coef_[0:7,:])

[[ -3.20653725   6.40656762  -3.90611558 ...  -4.11403016  -0.38076569
    0.15903416]
 [  5.5837932  -12.09312526   7.69070901 ...   8.15488257   0.14977493
   -0.33181581]
 [ -2.21877222   5.3074538   -3.53228719 ...  -3.77146225   0.21559138
    0.16126287]]


In [82]:
pred=lda.predict(X_autosc)
print(np.unique(pred, return_counts=True))

(array(['DMMP', 'TATP', 'acetone'], dtype='<U7'), array([13, 14, 16]))


In [83]:
print(confusion_matrix(pred, Y))
print(classification_report(Y, pred, digits=2))

[[13  0  0]
 [ 0 14  0]
 [ 1  0 15]]
              precision    recall  f1-score   support

        DMMP       1.00      0.93      0.96        14
        TATP       1.00      1.00      1.00        14
     acetone       0.94      1.00      0.97        15

    accuracy                           0.98        43
   macro avg       0.98      0.98      0.98        43
weighted avg       0.98      0.98      0.98        43



In [84]:
scores = pd.DataFrame(data = scores_lda, columns = ['LV1','LV2']) # latent variables
scores.index = df.index
scores

LV1       LV2
Sample_id                      
TATP_1      46.112304  0.670368
TATP_2      47.343863 -0.115144
TATP_3      46.363503 -1.218734
TATP_4      43.967896 -1.388386
TATP_5      46.786435  0.218842
TATP_6      49.267431  0.251943
TATP_7      47.555055  1.264297
TATP_8      47.303082 -0.958874
TATP_9      47.628474 -0.649431
TATP_10     48.516529  0.540621
TATP_11     47.554719  0.252962
TATP_12     48.328725 -0.070085
TATP_13     46.853905  0.774693
TATP_14     47.987114  0.486200
Acetone_1  -24.082713  2.369483
Acetone_2  -23.040827  0.691229
Acetone_3  -23.166973 -0.062212
Acetone_4  -22.393371  1.372359
Acetone_5  -22.218066  1.139077
Acetone_6  -22.193414  0.453003
Acetone_7  -22.979775  1.635516
Acetone_8  -22.677345  2.564098
Acetone_9  -21.335014  1.895689
Acetone_10 -22.675294  2.827313
Acetone_11 -22.934043  2.159481
Acetone_12 -23.820339  3.123450
Acetone_13 -24.335819  3.104954
Acetone_14 -22.573285  1.310480
Acetone_15 -22.933071  1.123495
DMMP_1     -23.613054 -0.799355
DMMP_2     -24.209288 -1.538563
DMMP_3     -22.004888 -1.841000
DMMP_4     -23.175629  1.466846
DMMP_5     -20.666913 -1.398759
DMMP_6     -22.723874 -0.926740
DMMP_7     -22.517996 -2.068477
DMMP_8     -21.775889 -2.539084
DMMP_9     -22.381187 -2.524170
DMMP_10    -22.890069 -2.386579
DMMP_11    -22.901537 -2.342106
DMMP_12    -23.962284 -2.740665
DMMP_13    -22.984638 -2.876856
DMMP_14    -22.402441 -3.251182

In [85]:
scores = pd.concat([scores, Y], axis = 1)
print(scores)

                  LV1       LV2    Class
Sample_id                               
TATP_1      46.112304  0.670368     TATP
TATP_2      47.343863 -0.115144     TATP
TATP_3      46.363503 -1.218734     TATP
TATP_4      43.967896 -1.388386     TATP
TATP_5      46.786435  0.218842     TATP
TATP_6      49.267431  0.251943     TATP
TATP_7      47.555055  1.264297     TATP
TATP_8      47.303082 -0.958874     TATP
TATP_9      47.628474 -0.649431     TATP
TATP_10     48.516529  0.540621     TATP
TATP_11     47.554719  0.252962     TATP
TATP_12     48.328725 -0.070085     TATP
TATP_13     46.853905  0.774693     TATP
TATP_14     47.987114  0.486200     TATP
Acetone_1  -24.082713  2.369483  acetone
Acetone_2  -23.040827  0.691229  acetone
Acetone_3  -23.166973 -0.062212  acetone
Acetone_4  -22.393371  1.372359  acetone
Acetone_5  -22.218066  1.139077  acetone
Acetone_6  -22.193414  0.453003  acetone
Acetone_7  -22.979775  1.635516  acetone
Acetone_8  -22.677345  2.564098  acetone
Acetone_9  -21.3

In [86]:
print('explained variance ratio (first four components) with LDA: %s'
  % str(lda.explained_variance_ratio_))

explained variance ratio (first four components) with LDA: [0.99803038 0.00196962]


In [87]:
lda.explained_variance_ratio_

array([0.99803038, 0.00196962])

In [88]:
loadings = pd.DataFrame(lda.coef_.T[:,0:2],columns = ['LV1','LV2'])
loadings["Attributes"] = df.iloc[:,1:].columns
loadings

LV1        LV2 Attributes
0    -3.206537   5.583793       0.52
1     6.406568 -12.093125       0.54
2    -3.906116   7.690709       0.56
3   -10.025207  21.614206       0.58
4    -0.326416   0.722161        0.6
..         ...        ...        ...
663  -5.922316  13.582151      13.78
664  -2.700182   5.733327       13.8
665  -4.114030   8.154883      13.82
666  -0.380766   0.149775      13.84
667   0.159034  -0.331816      13.86

[668 rows x 3 columns]

In [89]:
#Scores plot
import plotly.express as px
fig = px.scatter(scores, x="LV1", y="LV2", color="Class", hover_data=['Class'])
fig.update_xaxes(zeroline=True, zerolinewidth=1, zerolinecolor='Black')
fig.update_yaxes(zeroline=True, zerolinewidth=1, zerolinecolor='Black')
fig.update_layout(
    height=600,
    width=800,
    title_text='Scores Plot')
fig.show()

## PLSDA

In [90]:
Y = Y.astype('category')
Y

Sample_id
TATP_1           TATP
TATP_2           TATP
TATP_3           TATP
TATP_4           TATP
TATP_5           TATP
TATP_6           TATP
TATP_7           TATP
TATP_8           TATP
TATP_9           TATP
TATP_10          TATP
TATP_11          TATP
TATP_12          TATP
TATP_13          TATP
TATP_14          TATP
Acetone_1     acetone
Acetone_2     acetone
Acetone_3     acetone
Acetone_4     acetone
Acetone_5     acetone
Acetone_6     acetone
Acetone_7     acetone
Acetone_8     acetone
Acetone_9     acetone
Acetone_10    acetone
Acetone_11    acetone
Acetone_12    acetone
Acetone_13    acetone
Acetone_14    acetone
Acetone_15    acetone
DMMP_1           DMMP
DMMP_2           DMMP
DMMP_3           DMMP
DMMP_4           DMMP
DMMP_5           DMMP
DMMP_6           DMMP
DMMP_7           DMMP
DMMP_8           DMMP
DMMP_9           DMMP
DMMP_10          DMMP
DMMP_11          DMMP
DMMP_12          DMMP
DMMP_13          DMMP
DMMP_14          DMMP
Name: Class, dtype: category
Categories (3, 

In [91]:
Y = Y.cat.codes
Y

Sample_id
TATP_1        1
TATP_2        1
TATP_3        1
TATP_4        1
TATP_5        1
TATP_6        1
TATP_7        1
TATP_8        1
TATP_9        1
TATP_10       1
TATP_11       1
TATP_12       1
TATP_13       1
TATP_14       1
Acetone_1     2
Acetone_2     2
Acetone_3     2
Acetone_4     2
Acetone_5     2
Acetone_6     2
Acetone_7     2
Acetone_8     2
Acetone_9     2
Acetone_10    2
Acetone_11    2
Acetone_12    2
Acetone_13    2
Acetone_14    2
Acetone_15    2
DMMP_1        0
DMMP_2        0
DMMP_3        0
DMMP_4        0
DMMP_5        0
DMMP_6        0
DMMP_7        0
DMMP_8        0
DMMP_9        0
DMMP_10       0
DMMP_11       0
DMMP_12       0
DMMP_13       0
DMMP_14       0
dtype: int8

In [92]:
regr_pls = PLSR(n_components=3)
PLS_scores=regr_pls.fit_transform(X_autosc,Y)
print(regr_pls.x_scores_)

[[  5.9136147   21.02344212   1.00324803]
 [  8.93645708  24.28032944  -5.07207308]
 [  5.9602526   20.93864855   1.20952224]
 [  5.47182091  17.97114414   0.64547739]
 [  6.55665755  22.97486619  -1.36223215]
 [  5.36968247  19.00999047  -1.14326341]
 [  6.36136089  21.4814855    1.15676636]
 [  6.37475593  19.99885239   0.83091575]
 [  5.73436672  23.54366566   1.22800325]
 [  5.7254621   23.88761091   1.16982672]
 [  5.78774099  24.6166465    1.09066426]
 [  6.75150238  20.97598163   1.3201249 ]
 [  6.16571887  20.31948797   0.46142543]
 [  6.14154258  20.10945974   0.31742087]
 [ -6.64202927  -3.38641034 -10.87053066]
 [ -6.67073719  -3.07279291 -11.20350304]
 [ -5.41615706  -5.28570223  -3.88735152]
 [ -5.25816365  -5.2917655   -3.96103377]
 [ -6.14168325  -4.49803358  -3.22511124]
 [ -5.54741143  -5.21891015  -3.33571541]
 [ -7.50100984  -2.7878139   -8.00066978]
 [ -9.66665584  -0.22829936  -0.88579266]
 [-11.58866619   2.50646213   0.506044  ]
 [-13.08206995   4.04001466   1.79

In [93]:
scores = regr_pls.x_scores_
scores

array([[  5.9136147 ,  21.02344212,   1.00324803],
       [  8.93645708,  24.28032944,  -5.07207308],
       [  5.9602526 ,  20.93864855,   1.20952224],
       [  5.47182091,  17.97114414,   0.64547739],
       [  6.55665755,  22.97486619,  -1.36223215],
       [  5.36968247,  19.00999047,  -1.14326341],
       [  6.36136089,  21.4814855 ,   1.15676636],
       [  6.37475593,  19.99885239,   0.83091575],
       [  5.73436672,  23.54366566,   1.22800325],
       [  5.7254621 ,  23.88761091,   1.16982672],
       [  5.78774099,  24.6166465 ,   1.09066426],
       [  6.75150238,  20.97598163,   1.3201249 ],
       [  6.16571887,  20.31948797,   0.46142543],
       [  6.14154258,  20.10945974,   0.31742087],
       [ -6.64202927,  -3.38641034, -10.87053066],
       [ -6.67073719,  -3.07279291, -11.20350304],
       [ -5.41615706,  -5.28570223,  -3.88735152],
       [ -5.25816365,  -5.2917655 ,  -3.96103377],
       [ -6.14168325,  -4.49803358,  -3.22511124],
       [ -5.54741143,  -5.21891

In [94]:
scores = pd.DataFrame(scores, columns = ['LV1','LV2','LV3'])
scores.index = df.index
y = df.Class
scores = pd.concat([scores, y], axis = 1)
scores

LV1        LV2        LV3    Class
Sample_id                                           
TATP_1       5.913615  21.023442   1.003248     TATP
TATP_2       8.936457  24.280329  -5.072073     TATP
TATP_3       5.960253  20.938649   1.209522     TATP
TATP_4       5.471821  17.971144   0.645477     TATP
TATP_5       6.556658  22.974866  -1.362232     TATP
TATP_6       5.369682  19.009990  -1.143263     TATP
TATP_7       6.361361  21.481485   1.156766     TATP
TATP_8       6.374756  19.998852   0.830916     TATP
TATP_9       5.734367  23.543666   1.228003     TATP
TATP_10      5.725462  23.887611   1.169827     TATP
TATP_11      5.787741  24.616647   1.090664     TATP
TATP_12      6.751502  20.975982   1.320125     TATP
TATP_13      6.165719  20.319488   0.461425     TATP
TATP_14      6.141543  20.109460   0.317421     TATP
Acetone_1   -6.642029  -3.386410 -10.870531  acetone
Acetone_2   -6.670737  -3.072793 -11.203503  acetone
Acetone_3   -5.416157  -5.285702  -3.887352  acetone
Acetone_4   -5.258164  -5.291766  -3.961034  acetone
Acetone_5   -6.141683  -4.498034  -3.225111  acetone
Acetone_6   -5.547411  -5.218910  -3.335715  acetone
Acetone_7   -7.501010  -2.787814  -8.000670  acetone
Acetone_8   -9.666656  -0.228299  -0.885793  acetone
Acetone_9  -11.588666   2.506462   0.506044  acetone
Acetone_10 -13.082070   4.040015   1.790115  acetone
Acetone_11 -12.933883   3.733533   1.955078  acetone
Acetone_12 -14.356868   4.326837   1.343619  acetone
Acetone_13 -14.766462   4.971425   1.629475  acetone
Acetone_14 -14.160739   4.527534   5.862748  acetone
Acetone_15 -14.337191   4.244389   7.334027  acetone
DMMP_1       0.499019 -15.017029   3.195038     DMMP
DMMP_2       0.436460 -15.235835   3.326701     DMMP
DMMP_3       0.716906 -15.077126   3.402461     DMMP
DMMP_4      -4.360945  -8.426899   3.022928     DMMP
DMMP_5       2.616661 -18.867257   3.673611     DMMP
DMMP_6       2.581632 -19.058649   3.735295     DMMP
DMMP_7       5.644873 -22.774582   0.713169     DMMP
DMMP_8       5.426889 -22.074666   0.766650     DMMP
DMMP_9       4.555422 -22.341719   2.983462     DMMP
DMMP_10      4.598459 -22.490621   3.066230     DMMP
DMMP_11      8.731419 -28.093603  -0.321665     DMMP
DMMP_12      8.415509 -27.596267  -0.195567     DMMP
DMMP_13     10.564484 -31.328585  -2.703781     DMMP
DMMP_14     10.392002 -31.329239  -2.571755     DMMP

In [95]:
loadings = pd.DataFrame(regr_pls.x_loadings_,columns = ["LV1",'LV2','LV3'])
loadings["Attributes"] = df.iloc[:,1:].columns
loadings

LV1       LV2       LV3 Attributes
0    0.068621  0.045250  0.011553       0.52
1    0.069285  0.045081  0.014468       0.54
2    0.067850  0.045739  0.016649       0.56
3    0.069053  0.045483  0.009509       0.58
4    0.068170  0.045717  0.017263        0.6
..        ...       ...       ...        ...
663  0.069022  0.045393  0.014746      13.78
664  0.066798  0.045850  0.011274       13.8
665  0.068128  0.045850  0.005045      13.82
666  0.068407  0.045647  0.008282      13.84
667  0.025541  0.026703  0.076039      13.86

[668 rows x 4 columns]

In [96]:
import plotly.express as px
fig = px.scatter(scores, x="LV1", y="LV2", color="Class", hover_data=['Class'])
fig.update_xaxes(zeroline=True, zerolinewidth=1, zerolinecolor='Black')
fig.update_yaxes(zeroline=True, zerolinewidth=1, zerolinecolor='Black')
fig.update_layout(
    height=600,
    width=800,
    title_text='Scores Plot')
fig.show()